version: "3.8"

services:
  db:
    image: postgres
    container_name: db_postgresql
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: 12345
    ports:
      - 80:5432
    volumes:
      - db:/data/db

volumes:
  db: